[package]
name = "lalrpop-lox"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22"

[dependencies]
lalrpop-util = { version = "0.22", features = ["lexer"] }
lox-ast = { workspace = true }

[lib]
name = "lalrpop_lox"
path = "src/lib.rs"
