[package]
name = "lalrpop-lox"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { workspace = true }

[dependencies]
lalrpop-util = { workspace = true, features = ["lexer"] }
lox-ast = { workspace = true }

[lib]
name = "lalrpop_lox"
path = "src/lib.rs"
