[package]
name = "chumsky-lox"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { workspace = true }
lox-ast = { workspace = true }

[lib]
name = "chumsky_lox"
path = "src/lib.rs"

[[bin]]
name = "chumsky-lox"
path = "src/main.rs"