[package]
name = "winnow-lox"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = { workspace = true }
lox-ast = { workspace = true }

[lib]
name = "winnow_lox"
path = "src/lib.rs"

[[bin]]
name = "winnow-lox"
path = "src/main.rs"
