[package]
name = "parser-comparison-simple"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
nom-lox = { path = "../nom-lox" }
lox-ast = { path = "../lox-ast" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
